/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.File;

public class App {

    //  String inputFilePath = app/src/main/resources/imageBmp.bmp
    //  String outputFilePath = app/src/main/resources/imageBmp2.bmp
    public static void main(String[] args) {
        System.out.println(testFunction(args));
    }

    public static String testFunction(String[] argsPar){


            if (argsPar.length == 3) {
                String inputFilePath = argsPar[0];
                String outputFilePath = argsPar[1];


                Bitmap bitMap = new Bitmap(inputFilePath);


                if (argsPar[2].equals("convertImageToGray")) {
                    bitMap.convertImageToGray();
                }
                if (argsPar[2].equals("mirrorImageVertically")) {
                    bitMap.mirrorImageVertically();
                }
                if (argsPar[2].equals("mirrorImageHorizontally")) {
                    bitMap.mirrorImageHorizontally();
                }

                bitMap.writeNewImage(outputFilePath);

                return (checkIfCreated(outputFilePath));
            } else {
                return ("args invalid");
            }


    }


    public static String checkIfCreated(String outputFilePath){
        File outputFile = new File(outputFilePath);
        if (outputFile.exists()) {
            return "Done .. New image saved to " + outputFilePath;
        } else {
            return "Error: New image was not created.";
        }
    }




}
